algorithm: mola_lo
lidar_topic: /points2/decompressed
imu_topic: null
base_link_frame: depth_camera_link
lidar_fixed_pose_xyz_ypr_deg: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
imu_fixed_pose_xyz_ypr_deg: null
ignore_lidar_pose_from_tf: true
ignore_imu_pose_from_tf: true
deskew_method: MotionCompensationMethod::Linear
use_imu_for_lio: false
icp_pipeline: lidar3d-gicp.yaml
minimum_range_m: 0.5
maximum_range_m: 70.0
voxel_parameters:
  pipeline_default: true
local_map_parameters:
  min_nearby_poses_occupied: 2
  simplemap_min_nearby_poses: 2
trajectory_output: {topic: /tf, transform: map->depth_camera_link}
publish_tf: false
use_sim_time: true
